name: 'Yarn install with cache'
description: ''
runs:
  - name: Get yarn cache directory path
    id: yarn_cache_path
    run: echo "::set-output name=dir::$(yarn cache dir)"

  # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
  - uses: actions/cache@v1
    id: yarn_cache
    with:
      path: ${{ steps.yarn_cache_path.outputs.dir }}
      key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      restore-keys: ${{ runner.os }}-yarn-

  - name: Install packages
    id: yarn_install
    run: yarn install
