version: '3.2'
services:
  app:
    build: ./test/e2e
    ports:
      - 8080:80
    volumes:
      - ./test/e2e/app:/app
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./packages:/app/packages
  cypress:
    image: cypress/included:4.5.0
    depends_on:
      - app
    environment:
      - CYPRESS_baseUrl=http://app
    volumes:
      - ./test/e2e/cypress:/app/cypress
      - ./test/e2e/cypress.json:/app/cypress.json
      - ./node_modules:/app/node_modules
      - ./.nyc_output:/app/.nyc_output
      - ./coverage/:/app/coverage
      - ./package.json:/app/package.json
  unit:
    build: ./test/unit
    volumes:
      - ./test/unit:/app/test/unit
      - ./node_modules:/app/node_modules
      - ./.nyc_output:/app/.nyc_output
      - ./coverage:/app/coverage
      - ./package.json:/app/package.json
      - ./packages:/app/packages
