version: '3.2'
services:
  cypress:
    build: ./cypress
    ports:
      - 3000:3000
    volumes:
      - ./cypress:/e2e/cypress
      - ./cypress.json:/e2e/cypress.json
      - ./tsconfig.json:/e2e/tsconfig.json
      - ./package.json:/e2e/package.json
      - ./node_modules:/e2e/node_modules
      - ./packages:/e2e/packages
