name: Tests
on:
  - push

jobs:
  # Install yarn packages and setup project
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

      - name: Install dependencies
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Cache workspace
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

  # Run unit and e2e tests
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}
      - name: Install cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
            headless: true

      - name: Build packages
        run: yarn build
      - name: Run cypress (e2e and unit tests)
        run: yarn cypress

      # Upload coverage report to codecov and codacy
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v0.2.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info

