name: E2E and Unit Tests
on:
  - push

jobs:
  # Install yarn packages and setup project
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive

  # Run unit and e2e tests
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Build packages
        run: yarn build

      - name: Start dev server
        run: yarn dev &
      - name: Wait for dev server to start
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http://localhost:3000
      - name: Run cypress (e2e and unit tests)
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          config-file: ./cypress/cypress.json
          spec: ./cypress/integration/bootstrap.js

      # Upload coverage report to codecov and codacy
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./cypress/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v0.2.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./cypress/coverage/lcov.info

