name: Codacy

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
  schedule:
    - cron: '0 14 * * 0'

jobs:
  analyze:
    name: Codacy Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2

    # If this run was triggered by a pull request event, then checkout
    # the head of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}

    - name: Run codacy-analysis-cli
      uses: codacy/codacy-analysis-cli-action@1.1.0
      with:
        output: result.sarif
        format: sarif
        directory: packages
        gh-code-scanning-compat: true
        max-allowed-issues: 1000

    - name: Upload result
      uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: result.sarif
