name: Tests
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install packages
    - name: Get yarn cache directory path
      id: yarn_cache_path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
    - uses: actions/cache@v1
      id: yarn_cache
      with:
        path: ${{ steps.yarn_cache_path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: ${{ runner.os }}-yarn-
    - name: Install packages
      id: yarn_install
      run: yarn install

    # Run unit tests
    - name: Run unit tests
      run: yarn test:unit

    # Run e2e tests
    #- name: Start e2e test server
    #  run: yarn test:e2e-server &
    #- name: Run e2e tests
    #  run: yarn test:e2e

    # Might be automatically done in e2e
    # Generate coverage report, upload to codecov
    - name: Generate coverage report
      run: yarn test:report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
