name: Tests
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/yarn
    - uses: ./.github/actions/unit
    #- uses: ./.github/actions/e2e
    # Might be automatically done in e2e
    - name: Generate coverage report
      run: yarn test:report

    # Use the output from the coverage action
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage/coverage.json
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

    - name: Stop containers
      run: docker-compose down
