name: Tests
on:
  - push
  - pull_request

jobs:
  # Install yarn packages and setup project
  setup:
    - uses: actions/checkout@v2
    - name: Cache node_modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}

    - name: Install packages
      run: yarn --check-files --frozen-lockfile --non-interactive
    - name: Cache workspace
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}
        key: workspace-${{ github.sha }}

  # Run unit and e2e tests
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - name: Restore workspace cache
        uses: actions/cache@v1
        with:
          path: ${{ github.workspace }}
          key: workspace-${{ github.sha }}

      - name: Run unit tests
        run: yarn test:unit
      #- name: Start e2e test server
      #  run: yarn test:e2e-server &
      #- name: Run e2e tests
      #  run: yarn test:e2e

      # Might be automatically done by e2e
      # Generate coverage report, upload to codecov
      - name: Generate coverage report
        run: yarn test:report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

