on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Not using cache, we want fresh builds
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive

      - name: Publish packages to npm
        run: ./bin/publish ${{ github.ref }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          #body: TODO; Changelog??
