on:
  push:
    # Sequence of patterns matched against refs/tags
    # Push events to matching v*, i.e. v1.0, v20.15.10
    tags: [ v* ]

name: Publish
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Required for pushes to work
      - name: Prepare repo
        run: git checkout "${GITHUB_REF:10}"
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org
          always-auth: true

      # Not using cache, we want fresh builds
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive

      - name: Set Git config
        run: |
          git config --global user.name 'Christian Norrman'
          git config --global user.email 'christian@faxity.se'

      - name: Build packages
        run: yarn build --release

      - name: Publish packages
        run: ./bin/publish ${{ github.ref }}
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          #body: TODO refer to Changelog for every package
