on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          body: TODO; Changelog??

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive
      - name: Build the packages
        run: yarn build
      - name: Publish packages
        run: ./bin/publish ${{ github.ref }}
